PIALibrary/Sources/Util/Keychain.swift
Credentials may be unavailable while device is locked. Given that the VPN gets its credentials from the keychain, it may not be able to start in the background due to a restrictive keychain access level.
Raise to `AfterFirstUnlock`.
=> Relax keychain access level

PIALibrary/Sources/Core/Persistence/PlainStore.swift, PIALibrary/Sources/Library/Client+Preferences.swift, PIALibrary/Sources/Library/Persistence/UserDefaultsStore.swift, PIALibrary/Sources/Library/VPN/DefaultVPNProvider.swift, PIALibraryTests/VPNTests.swift
Currently hardcoded to `false`. Default to `false`, but make it an option.
=> Add preference to disconnect VPN on sleep

PIALibrary.podspec, PIALibrary/Sources/Core/Persistence/PlainStore.swift, PIALibrary/Sources/Core/VPN/VPNConfiguration.swift, PIALibrary/Sources/Library/Client+Preferences.swift, PIALibrary/Sources/Library/Persistence/UserDefaultsStore.swift, PIALibrary/Sources/Library/VPN/DefaultVPNProvider.swift, PIALibrary/Sources/VPN/PIATunnelProfile.swift, PIALibrary/Sources/VPN/PIATunnelProvider+Profile.swift, Podfile, Podfile.lock
PIATunnel 1.1.3 breaks with removal of socketType, deprecation was too expensive. Drop preferredPort, leave it protocol-specific.
=> Update API to PIATunnel 1.1.3

PIALibrary/Sources/Library/Client+Preferences.swift
Custom configuration for `PIATunnelProfile` must fall back to defaults in case any error occurs.
=> Fall back to default VPN custom configuration

PIALibrary/Sources/Util/Keychain.swift
Only meaningful in setter, restriction is unnecessary in getter.
Fixes #9
=> Remove access qualifier from password read query

Package.swift
- This PR depends on the following PR to be merged first:
https://github.com/pia-foss/mobile-ios-wireguard/pull/4
=> PIA-906: Set swift-tools to 5.8 (for XCode 14 compatibility)

Package.swift
This PR fixes a production bug which was causing go runtime to crash. Until we investigate the latests changes on WG, we need to revert to a working WG version.
=> PIA-1059: Update wg dependency to a previous working version

Sources/PIALibrary/Account/DefaultAccountProvider.swift
Update `DefaultAccountProvider` access control so that it can be extended from the client app.
This PR is required to be merged first before this other one:
https://github.com/pia-foss/mobile-ios/pull/51
=> PIA-1058: Update access control on default AccountProvider

Sources/PIALibrary/Client+Configuration.swift, Sources/PIALibrary/Client+Preferences.swift, Sources/PIALibrary/Persistence/PlainStore.swift, Sources/PIALibrary/Persistence/UserDefaultsStore.swift, Sources/PIALibrary/VPN/IKEv2Profile.swift, Sources/PIALibrary/VPN/PIATunnelProfile.swift, Sources/PIALibrary/VPN/PIAWGTunnelProfile.swift
It introduces the changes to make wireguard the default protocol on new installations and the logic to allow us to migrate to wireguard those on ikev2 with default settings.
_Tests were performed with the application changes introduced [here](https://github.com/pia-foss/mobile-ios/pull/73)_
=> PIA-1291: Make wireguard the default option

Sources/PIALibrary/Client+Configuration.swift
**Summary**
This PR adds the tvOS QR Sign in token to `Client`
=> PIA-1544: Add tvOS token to Client in order to keep it in memory

Sources/PIALibrary/Account/CompositionRoot/AccountFactory.swift, Sources/PIALibrary/Account/Domain/AuthTokenSerializer.swift, Sources/PIALibrary/Account/Domain/Entities/APIToken.swift, Sources/PIALibrary/Account/Domain/Entities/VpnToken.swift, Sources/PIALibrary/Account/Domain/UseCases/APITokenUseCase.swift, Sources/PIALibrary/Account/Domain/UseCases/VpnTokenUseCase.swift, Sources/PIALibrary/Persistence/KeychainStore.swift, Sources/PIALibrary/Persistence/SecureStore.swift, Sources/PIALibrary/Util/Keychain.swift, Sources/PIALibrary/WebServices/PIAWebServices.swift, Tests/PIALibrary.xctestplan, Tests/PIALibraryTests/AuthTokenSerializerTests.swift
- Get previously stored API token and Vpn Token from the keychain
- Handle data serialization when retrieving the tokens from the Keychain and when updating the tokens in the keychain
- Added unit tests to tokens serialization
NOTE: Calling the API to refresh the tokens will be handled in the next PR
=> PIA-1822: [Account migration] Get and save auth tokens from the Keychain store

Sources/PIALibrary/Account/CompositionRoot/AccountFactory.swift, Sources/PIALibrary/Account/Data/APITokenProvider.swift, Sources/PIALibrary/Account/Data/Networking/RefreshApiTokenRequestConfiguration.swift, Sources/PIALibrary/Account/Data/Networking/RefreshVpnTokenRequestConfiguration.swift, Sources/PIALibrary/Account/Data/RefreshAuthTokensChecker.swift, Sources/PIALibrary/Account/Data/VpnTokenProvider.swift, Sources/PIALibrary/Account/Domain/UseCases/RefreshAPITokenUseCase.swift, Sources/PIALibrary/Account/Domain/UseCases/RefreshVpnTokenUseCase.swift, Sources/PIALibrary/Common/CompositionRoot/NetworkRequestFactory.swift, Sources/PIALibrary/Common/Data/Extensions/TimeInterval+Extensions.swift, Sources/PIALibrary/Common/Data/Networking/Entities/NetworkRequestError.swift, Sources/PIALibrary/Common/Data/Networking/Interfaces/NetworkRequestConfigurationType.swift, Sources/PIALibrary/Common/Data/Networking/NetworkRequestClient.swift, Tests/PIALibraryTests/Mocks/APITokenProviderMock.swift, Tests/PIALibraryTests/Mocks/NetworkRequestConfigurationMock.swift, Tests/PIALibraryTests/Mocks/RefreshAPITokenUseCaseMock.swift, Tests/PIALibraryTests/Mocks/RefreshAuthTokensCheckerMock.swift, Tests/PIALibraryTests/Mocks/RefreshVpnTokenUseCaseMock.swift, Tests/PIALibraryTests/Mocks/VpnTokenProviderMock.swift, Tests/PIALibraryTests/NetworkRequestClientTests.swift, Tests/PIALibraryTests/RefreshAuthTokensCheckerTests.swift
- The Network client will make a call to check whether the auth tokens should be refreshed before performing a request if the configuration has the property `refreshAuthTokensIfNeeded` enabled -> this gives us the flexibility to execute requests with and without refreshing tokens
- The `RefreshAuthTokensChecker`  will check the expiration date of both the api and vpn tokens. And it will refresh them only if they are going to expire in less than **30** days. Note: we can adjust this number of days as we think is reasonable.
=> PIA-1882: Refresh Auth tokens if needed on every request

Sources/PIALibrary/Account/Data/ClientErrorMapper.swift, Sources/PIALibrary/Account/Data/Networking/LoginLinkRequestConfiguration.swift, Sources/PIALibrary/Account/Domain/UseCases/LoginUseCase.swift, Sources/PIALibrary/Account/Domain/UseCases/LogoutUseCase.swift, Sources/PIALibrary/Account/Domain/UseCases/RefreshAPITokenUseCase.swift, Sources/PIALibrary/Account/Domain/UseCases/RefreshVpnTokenUseCase.swift, Sources/PIALibrary/Common/Data/Networking/Entities/NetworkRequestError.swift, Sources/PIALibrary/Common/Data/Networking/NetworkRequestClient.swift, Tests/PIALibraryTests/LoginUseCaseTests.swift, Tests/PIALibraryTests/Mocks/APITokenProviderMock.swift, Tests/PIALibraryTests/Mocks/File.swift, Tests/PIALibraryTests/Mocks/VpnTokenProviderMock.swift, Tests/PIALibraryTests/NetworkRequestClientTests.swift, Tests/PIALibraryTests/RefreshAuthTokensCheckerTests.swift
This PR contains the `LoginUseCase` that performs the following requests:
- Login with credentials
- Login with receipt
- Request a login link via email
Note:
There is a utility struct `ClientErrorMapper` that maps the `NetworkRequestError` to a `ClientError` (the one that the app is expecting). This struct is not used anywhere yet. The idea is to use it on the `PIAWebServices` layer. But I would like to get some feedback so far about it.
=> PIA-1841: Login with creds and receipt

Sources/PIALibrary/Account/CompositionRoot/AccountFactory.swift, Sources/PIALibrary/Account/Data/Networking/AccountDetailsRequestConfiguration.swift, Sources/PIALibrary/Account/Data/Networking/LoginLinkRequestConfiguration.swift, Sources/PIALibrary/Account/Data/Networking/LoginRequestConfiguration.swift, Sources/PIALibrary/Account/Data/Networking/RefreshApiTokenRequestConfiguration.swift, Sources/PIALibrary/Account/Data/Networking/RefreshVpnTokenRequestConfiguration.swift, Sources/PIALibrary/Account/Data/Networking/SignupRequestConfiguration.swift, Sources/PIALibrary/Account/Data/Networking/UpdateAccountRequestConfiguration.swift, Sources/PIALibrary/Account/DefaultAccountProvider.swift, Sources/PIALibrary/Account/Domain/UseCases/LogoutUseCase.swift, Sources/PIALibrary/Account/Domain/UseCases/UpdateAccountUseCase.swift, Sources/PIALibrary/Common/Data/Extensions/Bool+Extensions.swift, Sources/PIALibrary/Common/Data/Extensions/String+Extensions.swift, Sources/PIALibrary/Common/Data/Networking/Interfaces/NetworkRequestConfigurationType.swift, Sources/PIALibrary/Common/Data/Networking/NetworkConnectionRequestProvider.swift, Sources/PIALibrary/WebServices/PIAWebServices.swift, Tests/PIALibraryTests/Accounts/UpdateAccountUseCaseTests.swift, Tests/PIALibraryTests/Mocks/NetworkRequestConfigurationMock.swift
- Update account APIs (setEmail) with the option of reseting or not the password
- Added the optional `otherHeathers` property in `NetworkRequestConfigurationType` since one of the APIs to update account details requires the option to set another header for basic authentication
- Added unit tests to `UpdateAccountDetailsUseCase`
=> PIA-1849: Migrate update account APIs

Sources/PIALibrary/Account/CompositionRoot/AccountFactory.swift, Sources/PIALibrary/Account/Data/ClientErrorMapper.swift, Sources/PIALibrary/Account/Data/ClientStatusInformationDecoder.swift, Sources/PIALibrary/Account/Data/Networking/ClientStatusRequestConfiguration.swift, Sources/PIALibrary/Account/Data/RefreshAuthTokensChecker.swift, Sources/PIALibrary/Account/Domain/Entities/File.swift, Sources/PIALibrary/Account/Domain/UseCases/ClientStatusUseCase.swift, Sources/PIALibrary/Common/Data/Networking/Entities/NetworkRequestError.swift, Sources/PIALibrary/Common/Data/Networking/NetworkRequestClient.swift, Sources/PIALibrary/Daemons/ConnectivityDaemon.swift, Sources/PIALibrary/WebServices/PIAWebServices+Ephemeral.swift, Sources/PIALibrary/WebServices/PIAWebServices.swift, Tests/PIALibraryTests/Accounts/ClientStatusUseCaseTests.swift, Tests/PIALibraryTests/Accounts/Mocks/ClientStatusDecoderMock.swift, Tests/PIALibraryTests/Accounts/RefreshAuthTokensCheckerTests.swift
- Migration of the API `clientStatus` to Swift
- Update  `RefreshAuthTokensChecker` to only execute the refresh tokens request if there is not already a request in progress. This can happen because various UseCases call the `RefreshAuthTokenChecker` to refresh if needed before executing their requests. This update prevents executing multiple auth tokens refresh requests at the same time.
=> PIA-1844: Migrate client status API to native

Sources/PIALibrary/Account/CompositionRoot/AccountFactory.swift, Sources/PIALibrary/Account/Data/Networking/DeleteAccountRequestConfiguration.swift, Sources/PIALibrary/Account/DefaultAccountProvider.swift, Sources/PIALibrary/Account/Domain/UseCases/DeleteAccountUseCase.swift, Sources/PIALibrary/WebServices/PIAWebServices.swift, Sources/PIALibrary/WebServices/WebServices.swift, Tests/PIALibraryTests/Accounts/DeleteAccountUseCaseTests.swift
- Delete account API migration to Swift
- Remove auth tokens after deleting account
=> PIA-1932: Migrate delete account API to native

Sources/PIALibrary/Account/CompositionRoot/AccountFactory.swift, Sources/PIALibrary/Account/Data/Networking/FeatureFlagsRequestConfiguration.swift, Sources/PIALibrary/Account/DefaultAccountProvider.swift, Sources/PIALibrary/Account/Domain/Entities/FeatureFlagsInformation.swift, Sources/PIALibrary/Account/Domain/UseCases/FeatureFlagsUseCase.swift, Sources/PIALibrary/WebServices/PIAWebServices.swift, Sources/PIALibrary/WebServices/WebServices.swift, Tests/PIALibraryTests/Accounts/FeatureFlagsUseCaseTests.swift
- Migrate the feature flags network request to Swift native
- Automated tests to cover the success scenario and the posible errors returned
=> KM-4537: Migrate feature flags api to native

Sources/PIALibrary/Account/Data/ClientErrorMapper.swift, Sources/PIALibrary/Account/Data/DedicatedIPServerMapper.swift, Sources/PIALibrary/Account/Data/DedicatedIPTokenHandler.swift, Sources/PIALibrary/Account/Data/Networking/GetDedicatedIPsRequestConfiguration.swift, Sources/PIALibrary/Account/Data/Networking/RenewDedicatedIPRequestConfiguration.swift, Sources/PIALibrary/Account/Data/SignupInformationDataCoverter.swift, Sources/PIALibrary/Account/Domain/Entities/DedicatedIPInformation.swift, Sources/PIALibrary/Account/Domain/Interfaces/DedicatedIPServerMapperType.swift, Sources/PIALibrary/Account/Domain/Interfaces/DedicatedIPTokenHandlerType.swift, Sources/PIALibrary/Account/Domain/UseCases/GetDedicatedIPsUseCase.swift, Sources/PIALibrary/Account/Domain/UseCases/RenewDedicatedIPUseCase.swift, Sources/PIALibrary/Client+Providers.swift, Sources/PIALibrary/Common/Data/Networking/Entities/NetworkRequestError.swift, Sources/PIALibrary/Mock/MockDedicatedIPServerMapper.swift, Sources/PIALibrary/Mock/MockGetDedicatedIPsUseCase.swift, Sources/PIALibrary/Mock/MockRenewDedicatedIPUseCase.swift, Sources/PIALibrary/Mock/MockServerProvider.swift, Sources/PIALibrary/Server/CompositionRoot/ServerProviderFactory.swift, Sources/PIALibrary/Server/DefaultServerProvider.swift, Sources/PIALibrary/WebServices/DedicatedIP.swift, Sources/PIALibrary/WebServices/PIAWebServices.swift, Sources/PIALibrary/WebServices/WebServices.swift, Tests/PIALibraryTests/Accounts/GetDedicatedIPsUseCaseTests.swift, Tests/PIALibraryTests/Accounts/RenewDedicatedIPUseCaseTests.swift
**Summary**
This PR migrates the renew dedicated IP and get dedicated ip servers to Swift native.
It also adds unit tests for the use cases.
=> PIA-1845: Add Dedicated IP native endpoint

Sources/PIALibrary/Account/DefaultAccountProvider.swift, Sources/PIALibrary/Account/Domain/UseCases/LoginUseCase.swift, Tests/PIALibraryTests/Accounts/LoginUseCaseTests.swift
- Update the error thrown from the login with credentials and receipt requests
=> KM-4542: Update error thrown from failed login request

Sources/PIALibrary/Account/DefaultAccountProvider.swift
- Execute the callback of the feature flags request on the main queue to avoid a crash on the app
=> KM-4542: Execute feature flags request callback on main queue

Sources/PIALibrary/Account/DefaultAccountProvider.swift
- Avoid crashing the app when calling the logout API (even if the user is already not authenticated)
=> KM-4542: Execute logout without precondition failure

Sources/PIALibrary/Server/CompositionRoot/ServerProviderFactory.swift
**Summary**
This PR exposes `ServerProviderFactory` to be used on the main target.
=> KM-4856: Made ServerProviderFactory public to be used on the main target

Sources/PIALibrary/Account/CompositionRoot/AccountFactory.swift, Sources/PIALibrary/Account/DefaultAccountProvider.swift, Sources/PIALibrary/Account/NativeAccountProvider.swift, Sources/PIALibrary/WebServices/DedicatedIP.swift, Sources/PIALibrary/WebServices/PIAWebServices+Ephemeral.swift, Sources/PIALibrary/WebServices/PIAWebServices.swift, Sources/PIALibrary/WebServices/WebServices.swift
**Summary**
This PR sets the account Kotlin library as the default endpoint provider. The account implementation based on the new networking engine remains in the code but it's not used.
=> Set Accounts Kotlin library as default endpoint provider
